main: fun.fifu.bookedit.BookEdit
version: 2.33
name: BookEdit
author: NekokeCore
# 接高版本插件定制，小白的QQ：3513353936
api-version: 1.13
commands:
  book:
    description: "主命令"
    usage: 命令输入有误！ /book help [命令] 查看帮助
